name: C/C++ Docker CI (build)
on: [push]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build container
        run: |
          cd dockerfiles
          docker build . -f Dockerfile.full -t weather-server
          
